version: '3.8'

services:
  backend:
    build:
      context: .
      # Pass variables from the .env file as build arguments
      args:
        - pinecone_api=${pinecone_api}
        - OPENAI_API_KEY=${OPENAI_API_KEY}
        - tier_1_auth_key=${tier_1_auth_key}
        - GEMINI_API_KEY=${GEMINI_API_KEY}
        - POSTGRES_URL=${POSTGRES_URL}
        - SQLITE_DB_PATH=${SQLITE_DB_PATH}
        - MAIL_USERNAME=${MAIL_USERNAME}
        - MAIL_PASSWORD=${MAIL_PASSWORD}
        - MAIL_FROM=${MAIL_FROM}
        - MAIL_PORT=${MAIL_PORT}
        - MAIL_SERVER=${MAIL_SERVER}
        - MAIL_FROM_NAME=${MAIL_FROM_NAME}
        - FRESHDESK_API_KEY=${FRESHDESK_API_KEY}
        - FRESHDESK_DOMAIN=${FRESHDESK_DOMAIN}
        - TICKET_QUEUE=${TICKET_QUEUE}
        - REDIS_HOST=${REDIS_HOST}
        - REDIS_PORT=${REDIS_PORT}
        - REDIS_PASSWORD=${REDIS_PASSWORD}
    container_name: eev-ai-backend
    ports:
      - "8056:8056"
    volumes:
      - checkpoints_data:/app/checkpoint.sqlite
    command: uvicorn main:app --host 0.0.0.0 --port 8056

volumes:
  checkpoints_data: